### ISSUE TITLE
Can't find a way to adjust font size for title.

### ISSUE THREAD

**Issue by rhyscoronado** [davigmacode/flutter_smart_select#1]
Since the `title` is expecting a `String`, I was hoping if you can change it to accept `Text` so the the title can be styled.

Right now the title when on an AlertDialog/Popup could be around 20 or 24.

**Comment by davigmacode** [comment]
Yes, you can customize the text style by configuring `modalConfig.headerStyle.textStyle`, it will also affect the search bar text style. Or if you want to build your own header you can configure `modalConfig.leading`. In the next release, I will add `modalConfig.leadingBuilder` and `modalConfig.trailingBuilder` so that it can be more robust, but I am still analyzing the parameters that must be returned to the function.
```
SmartSelect<T>.single/multiple(
  ...,
  ...,
  modalConfig: SmartSelectModalConfig(
    ...,
    ...,
    headerStyle: SmartSelectModalHeaderStyle(
      ...,
      ...,
      textStyle: TextStyle(fontSize: 26),
    ),
  ),
);
```
Actually you can customize almost everything, you can find more about [customization example here](https://github.com/davigmacode/flutter_smart_select/blob/master/example/lib/features_choices/choices_theme.dart) or you can find another useful configuration at the [API Reference](https://pub.dev/documentation/smart_select/latest/smart_select/smart_select-library.html). I'm sorry, I'm too lazy to rewrite the documentation in Readme 😄

**Comment by rhyscoronado** [comment]
hey thanks, guess I was too lazy to browse through all the examples too. lol

appreciate the work you've done here.

**Comment by Tchoupinax** [comment]
Hello @davigmacode 

I spend a lot of time to search through documentation and examples but i do not succeed to change the color of the title. I have a dark theme so the select input is almost invisible.

![image](https://user-images.githubusercontent.com/9136206/100275411-2a6bb600-2f60-11eb-9c89-424695f93697.png)

```dart
 SmartSelect<String>.single(
    modalConfig: S2ModalConfig(
        headerStyle: S2ModalHeaderStyle(
      textStyle: TextStyle(color: Colors.white),
    )),
    title: 'Framorks',
    modalStyle: S2ModalStyle(backgroundColor: Colors.white, ),
    tileBuilder: (context, state) {
      return S2Tile.fromState(
        state,
        isTwoLine: true,
        isLoading: false,
      );
    },
    value: 'flutter',
    choiceItems: [
      S2Choice<String>(value: 'ion', title: 'Ionic'),
      S2Choice<String>(value: 'flu', title: 'Flutter'),
      S2Choice<String>(value: 'rea', title: 'React Native'),
    ],
    onChange: print,
  )
]),
```

I looked into `modalStyle`, `modalHeaderStyle` (I guess it is for the screen which allows to select the choices), all another property that contains `style`. I really do not know how to search morever

However i can make amazing things with the modal ^^

![image](https://user-images.githubusercontent.com/9136206/100275660-93532e00-2f60-11eb-9045-ead555ebe4d2.png)

PS: i'm not an expert with Dart, maybe I'm missing something

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
