### ISSUE TITLE
Theme change dark/light not propagated in modals 

### ISSUE THREAD

**Issue by kuhnroyal** [davigmacode/flutter_smart_select#13]
If the app theme changes while dialog/page/bottomsheet is opened, then these changes are not being applied. Only the background color changes unless it is overridden.

The theming is correct after closing and reopening.

**Comment by davigmacode** [comment]
Hi @kuhnroyal, I apologize for this long response.

I imagine that the widget is used to change the theme of your application, and the `modalConfirm` is `true`, right? if so, the changes in the modal haven't changed the final value, because `onChange` hasn't been called yet, you have to call the `state.closeModal(confirmed: true)` to confirm the modal and call the `onChange`

Besides, the parameters in the `showDialog` and `showModalBottomSheet` cannot be changed dynamically, we must close and reopen them to take the effect, maybe someone has an idea to fix this.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
