### ISSUE TITLE
activeTitleStyle doesn't work

### ISSUE THREAD

**Issue by Okayo18** [davigmacode/flutter_smart_select#15]
choiceConfig: SmartSelectChoiceConfig(
          isGrouped: true,
          glowingOverscrollIndicatorColor: kPrimaryColor,
          style: SmartSelectChoiceStyle(
            activeColor: kPrimaryColor,
            checkColor: Colors.white70,
            activeTitleStyle: TextStyle(
                color: Colors.white70
            ),
          )
//          secondaryBuilder: (context, item) => CircleAvatar(
//            backgroundColor: kPrimaryColor,
//            child: Text('H')
//          )
        ),

#activeTitleStyle color doesn't work !

**Comment by davigmacode** [comment]
Hi @Okayo18, I apologize for this long response. 

You can use `choiceTitleBuilder` to build the custom choice title widget
```dart
SmartSelect<T>.[single|multiple](
  ...,
  choiceTitleBuilder: (context, item, filter) {
    return S2Text(
      text: item.title,
      style: TextStyle(
        color: item.selected ? Colors.blueAccent : Colors.black54
      ),
      highlight: filter,
      highlightColor: Colors.redAccent.withOpacity(.7),
    );
  },
);
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
