### ISSUE TITLE
colorize, stylize choiceItems. How can use different S2ChoiceStyle for each S2Choice item?

### ISSUE THREAD

**Issue by fehernyul** [davigmacode/flutter_smart_select#26]
Hi,

My use case needs to colorize every S2Choice item with different color (font or background).
Can I use S2Choice item's "meta" tag for this? How?

For example, I need that, the 'dev' chip sholud be green, the 'test' chip sholud be blue and the 'prod' chip sholud be red, 
![image](https://user-images.githubusercontent.com/25593792/95312562-61421b80-088f-11eb-9170-0b63e89fae71.png)

Thanks,
Gabor

**Comment by davigmacode** [comment]
Hi @fehernyul 

Sure you can use `meta` to store the `Color`, but still you should build your own choice item using `choiceBuilder`, because this package doesn't specifically support those features at this time.

You can try [chips_choice](https://pub.dev/packages/chips_choice) package, thanks to you, because of this issue I have an idea to update that package to support individual choice style in easy way. please check at these [example](https://github.com/davigmacode/flutter_chips_choice/blob/master/example/lib/main.dart#L168), you only need to add the `chips_choice` widget to your own modal.

Thanks

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
