### ISSUE TITLE
keyboard overlap with bottomsheet modal

### ISSUE THREAD

**Issue by alr2413** [davigmacode/flutter_smart_select#35]
Hi,
When you click on the filter text in a bottomsheet modal to type, the keyboard shows on top of that.
might help:
[https://github.com/flutter/flutter/issues/18564#issuecomment-519429440](https://github.com/flutter/flutter/issues/18564#issuecomment-519429440)

**Comment by iksent** [comment]
Really need to pass down isScrollControlled!
@davigmacode, please provide this option.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
