### ISSUE TITLE
I want to show modal without rendering any tile builder

### ISSUE THREAD

**Issue by aqualaguna** [davigmacode/flutter_smart_select#39]
i mean i want is like this
```
                   var temp = SmartSelect.single(
                      choiceItems: [
                        S2Choice(value: 'test1', title: 'test1'),
                        S2Choice(value: 'test2', title: 'test2')
                      ],
                    );
                    S2Choice result = await temp.showModal(context);
```

**Comment by amoo12** [comment]
hey, have you found a solution I need to implement something similar to that?

**Comment by somnium-labs** [comment]
See this.

https://github.com/davigmacode/flutter_smart_select/blob/ae57fc417f6dd9e0371a6535e7f859ad13e37d91/example/lib/features_modal/modal_function.dart

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
