### ISSUE TITLE
groupSort isn't defined

### ISSUE THREAD

**Issue by mantsap89** [davigmacode/flutter_smart_select#42]
I upgraded the smart select package to the latest version (4.3.2) and everything works fine but i have a problem with some options of choiceConfig. I checked the file choice_config.dart and is different from the choice_config.dart that you use in your example. 
My file is missing the class S2GroupSort.
I am posting the two screenshots below. Thanks in advance! 

![my_choice_config](https://user-images.githubusercontent.com/75331270/100780088-f8e86400-3411-11eb-865a-6803814a47b8.png)
![choice_conifg](https://user-images.githubusercontent.com/75331270/100780098-fb4abe00-3411-11eb-983a-bcb76e5b9b46.png)

**Comment by mantsap89** [comment]
I just noticed that you changed your choice_config,dart yesterday. I have downloaded the whole project about a week ago, thats why i have different code in your example. 
Will you fix and upload it again?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
