### ISSUE TITLE
TextStyle for top level "title" widget

### ISSUE THREAD

**Issue by chuckienorton** [davigmacode/flutter_smart_select#44]
Hello, 

This is an excellent package that has made our application so so much more professional feeling. 

I'm having a hard time styling the 'title' field - not modal title but original title shown before opening the modal. This is primarily for dark/light mode. In dark mode the title is invisible before clicking to open the modal. 

I see in #19 what looks like the same question but the answer only applies to the modal header title. 

Any help would be appreciated!

**Comment by Fabs97** [comment]
Hello there,

I've encountered the same issues and it feels like this amazing widget is powered down by this issue and it's a bit frustrating. Nonetheless, Smart Select is pretty fantastic, it would be great if this hiccup could be solved as well!

Thanks for any help!

**Comment by ospangler** [comment]
I'm looking for a solution to this too, it's really my only complaint with the package

**Comment by ospangler** [comment]
I found a solution to this using [invert_colors](https://pub.dev/packages/invert_colors). It's not the prettiest, but it works. Just wrap the Smart Select with it, and the titles will switch to something dark mode friendly. Hopefully this is a temporary thing until this package is updated.

**Comment by lffruhling** [comment]
Hello, the package is really excellent, however, I would like to customize the title, simple changes like padding adjustment, changing the icon and font would be great in a new version!

**Comment by chuckienorton** [comment]
> I found a solution to this using [invert_colors](https://pub.dev/packages/invert_colors). It's not the prettiest, but it works. Just wrap the Smart Select with it, and the titles will switch to something dark mode friendly. Hopefully this is a temporary thing until this package is updated.

Thanks so much for this recommend - this was the only solution that worked for me for now.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
