### ISSUE TITLE
 chipDeleteColor: Colors.red

### ISSUE THREAD

**Issue by cosmosdesigner** [davigmacode/flutter_smart_select#46]
When i apply color on chipDeleteColor, i get this error:
type 'MaterialColor' is not a subtype of type 'bool'

`S2Tile.fromState(
                            state,
                            hideValue: true,
                            title: const Text('Choisir un prestation'),
                            trailing: const Icon(Icons.add_circle_outline),
                            body: S2TileChips(
                              chipLength: state.valueObject.length,
                              chipLabelBuilder: (context, i) {
                                return Text(state.valueObject[i].title);
                              },
                              chipOnDelete: (i) => setState(() {
                                _prestations.remove(state.valueObject[i].value);
                              }),
                              chipColor: IntervenantThemeColors.primaryColor,
                              chipDeleteColor: Colors.red,
                            ),
                          ),`

Thx

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
