### ISSUE TITLE
S2Choice, selected property is not working. When I try to put all values as selected, there is no changes

### ISSUE THREAD

**Issue by Kasiyliy** [davigmacode/flutter_smart_select#51]
List<DateTime> _times = [];
....
    boxes = widget.carwash.boxes
        .map((e) => S2Choice<Box>(
              value: e,
              title: e.name,
            ))
        .toList();
    times = buttonListGenerator()
        .map((e) => S2Choice<DateTime>(
              value: e,
              title: DateHelper.getTime(e),
              selected: true,
            ))
        .toList();
....
SmartSelect<DateTime>.multiple(
                      title: 'Времена',
                      modalFilter: true,
                      value: _times,
                      modalFilterHint: 'Ищите время',
                      placeholder: 'Выберите время',
                      onChange: (state) {
                        _times = state.value;
                      },
                      choiceItems: times,
                      modalType: S2ModalType.bottomSheet,
                      tileBuilder: (context, state) {
                        return S2Tile.fromState(
                          state,
                          isTwoLine: true,
                          loadingText: "Загружается",
                          leading: Container(
                            width: 40,
                            alignment: Alignment.center,
                            child: const Icon(Icons.access_time_outlined),
                          ),
                        );
                      },
                    ),

**Comment by JoDeveloper** [comment]
same error !!!

**Comment by pvzuntil** [comment]
Has this problem been resolved.?

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
