### ISSUE TITLE
Testing the component

### ISSUE THREAD

**Issue by rodrigobastosv** [davigmacode/flutter_smart_select#6]
Hi man, first of all great package, thanks for you work.

I saw that the package is not tested, so i want to test the component on my side.

Right now i can't test the onChange callback for example.

It would help me a lot if you could export ChoicesItem for example, so i can test the stuff.

**Comment by davigmacode** [comment]
Thanks for using this package, hope will help a lot. 

I'm sorry i am not yet experienced with testing stuff using flutter, and i can't help provide version with exported ChoicesItem, because currently i'm working on version with breaking changes which is not use ChoicesItem again, but you can fork this package, modify and use it with your project, hope you will understand

Here is a little leak for the next version
- highlight search result
- choice item in grid layout
- and many more

**Comment by rodrigobastosv** [comment]
Thanks @davigmacode , maybe ill wait for the next release then.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
