### ISSUE TITLE
Change color of title

### ISSUE THREAD

**Issue by rodrigobastosv** [davigmacode/flutter_smart_select#62]
Is there a way to change color/style of the title?

On this example, i want to change the color of the Language text.

![image](https://user-images.githubusercontent.com/12686272/105395852-fa5a2f80-5bfd-11eb-8b82-64cef764423f.png)

**Comment by anhvietcr** [comment]
I spend more time and didn't work.
My solution is wrapper select by a Container with white background, so color of title alway is black.

**Comment by uitlaber** [comment]
```
...
modalType: S2ModalType.bottomSheet,
                        tileBuilder: (context, state) {
                          return S2Tile.fromState(
                            state,
                            title: Text( 'Your text',
                                style: TextStyle(color: Colors.green)),
                          );
                        },
                        value: value,
...
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
