### ISSUE TITLE
Scroll to active option

### ISSUE THREAD

**Issue by iksent** [davigmacode/flutter_smart_select#67]
Hello, thanks a lot for cool library!

My question: is it possible to scroll modal to active option?

<img width="300px" src="https://user-images.githubusercontent.com/32956521/106425937-8255fa00-6486-11eb-85f8-873b1fa58e8a.jpeg"></img>

I am using modalType = `S2ModalType.bottomSheet`

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
