### ISSUE TITLE
Customizing SmartSelectOption

### ISSUE THREAD

**Issue by antonbt** [davigmacode/flutter_smart_select#7]
Such a feature rich package. Thanks! However, it would be nice to be able to customize each list option. Why not implement a child parameter or make the required title parameter accept a type of Widget instead of just a String.

**Comment by davigmacode** [comment]
Hey Thanks for using this package, hope will help a lot.

Title must be a String because it also used in comparison with search text. 

You should try use [choiceConfig](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelect/choiceConfig.html) option, it has a lot of option to create custom builder:
- [title builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/titleBuilder.html)
- [subtitle builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/subtitleBuilder.html)
- [secondary builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/secondaryBuilder.html)
- [divider builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/dividerBuilder.html)
- [empty state builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/emptyBuilder.html)
- [group header builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/groupHeaderBuilder.html)
- [custom choice item builder](https://pub.dev/documentation/smart_select/latest/smart_select/SmartSelectChoiceConfig/builder.html)

**Comment by sklorde** [comment]
Using choiceConfig i can't change the value of the checkbox... do you have any tips?
And, what's the param "null" inside `onChange(null, bool)` function?

```
choiceConfig: SmartSelectChoiceConfig(
                useDivider: true,
                builder: (item, checked, onChange) {
                  return Container(
                    height: 55,
                    child: Padding(
                      padding: EdgeInsets.only(left: 20),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            item.title,
                            style: TextStyle(
                              fontSize: 15,
                            ),
                          ),
                          if (item.subtitle != 'Produto em falta')
                            Row(
                              children: [
                                Text(
                                  '+ ${item.subtitle}',
                                  style: TextStyle(
                                    fontSize: 15,
                                    color: Colors.green,
                                  ),
                                ),
                                Checkbox(
                                  value: checked,
                                  onChanged: (value) {
                                    onChange(null, value);
                                  },
                                )
                              ],
                            )
                          else
                            Container(),
                        ],
                      ),
                    ),
                  );
                },
              ),
```

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?
