### ISSUE TITLE
Package not working?

### ISSUE THREAD

**Issue by kanapkowyksiaze123** [davigmacode/flutter_smart_select#70]
Hi All,

I tried to copy-paste and run an example code, but it never works. I tried multiple builds and multiple flutter versions as well.
It does seem that some parameters are faulty or missing that is the message I receive from my compiler:
![image](https://user-images.githubusercontent.com/78852630/107501770-1ebf8100-6b98-11eb-93ef-0c73ec459039.png)

To be more specific there are a couple of issues, like assigning .selected parameter to the string within tileBuilder, so on. I am not sure if anyone would be able to help here, but if so - I would be highly grateful.

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
