### ISSUE TITLE
Position of dialog popup

### ISSUE THREAD

**Issue by Hawk30100** [davigmacode/flutter_smart_select#73]
Is there any way to control the position of the dialog popup? It seems like it is centered by default.

I would like to position the popup right below the select button.

**Comment by bartukaan** [comment]
same problem

**Comment by Hawk30100** [comment]
@bartukaan unfortunately, no :(

**Comment by bartukaan** [comment]
@Hawk30100 me too :/

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
