### ISSUE TITLE
Filter sometimes malfunction

### ISSUE THREAD

**Issue by leean912** [davigmacode/flutter_smart_select#74]
E/flutter (12184): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A S2Choices<String> was used after being disposed.
E/flutter (12184): Once you have called dispose() on a S2Choices<String>, it can no longer be used.
E/flutter (12184): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (12184): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (12184): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter (12184): #3      S2Choices.load.<anonymous closure> (package:smart_select/src/state/choices.dart:140:9)
E/flutter (12184): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (12184): #5      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (12184): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12184): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12184): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12184): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (12184): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12184): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (12184): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (12184): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (12184): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (12184): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by leean912** [comment]
Does anyone encounter this issue?

**Comment by leean912** [comment]
I guess it conflict with other text field

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
