### ISSUE TITLE
[Android] The color of navigation bar changes when bottom sheet opens

### ISSUE THREAD

**Issue by DonWasyl** [davigmacode/flutter_smart_select#75]
Hello, I've issue with navigation bar. In my application I have white navigation bar, but its changes when I open select bottom sheet

This is my code responsible for navigation bar color, and video where you can noticed how navigation bar changes color from white to black.

Do you know how to avoid it? Maybe is this a bug? ;) 

```
void main() async {
  final systemTheme = SystemUiOverlayStyle.light.copyWith(systemNavigationBarColor: Colors.white);

  SystemChrome.setSystemUIOverlayStyle(systemTheme);

  runApp(App());
}
```

https://user-images.githubusercontent.com/2080253/109387301-f312f980-7900-11eb-851a-565c61df366a.mp4

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by m-wasilewski** [comment]
@vasilich6107 I checked your version, but it doesn't help

**Comment by DonWasyl** [comment]
@vasilich6107  I checked your version, but it doesn't help

**Comment by vasilich6107** [comment]
@DonWasyl as I mentioned in my message the main goal of my release was to bring proper nullsafety support to the package
You can create issues in the repository of new package.
By the way - I not understand your issue.
The bottom sheet adds semitransparent overlay to the underlying widgets so it seems to work ok from the video perspective.

**Comment by DonWasyl** [comment]
The problem is related to navigation bar
It lost the color when bottom sheet has been opened

![Zrzut ekranu 2021-11-30 o 21 00 10](https://user-images.githubusercontent.com/2080253/144119120-797fc3af-604f-4a49-94a4-5c22e33674f6.png)

**Comment by vasilich6107** [comment]
Ah, I see now)
It is no obvious, cause bottom part is hidden by player controls

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
